# lrnt's zsh configuration file

# {{{ Options
autoload -U colors && colors
autoload -U compinit && compinit
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

setopt prompt_subst
setopt share_history

# Prevent the "no matches found" error when using wildcards
unsetopt nomatch

# Smart urls
autoload -U url-quote-magic
zle -N self-insert url-quote-magic

# Enable fuzzy matching for autocomplete
zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'

# Enable menu select in zsh autocomplete
zstyle ':completion:*' menu select

# Ignore origin branches in git checkout
zstyle ':completion:*:*:git-checkout:*' ignored-patterns 'origin/*'

# Ignore certain extensions when autocompleting for vim
zstyle ':completion:*:*:vi(m|):*' ignored-patterns '*.pyc'

# Ignore .retry files when autocompleting ansible-playbook
zstyle ':completion:*:*:ansible-playbook:*' ignored-patterns '*.retry'

# History
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt inc_append_history
setopt share_history # share command history data
# }}}

# {{{ Load snippets
for snippets ($HOME/.config/zsh/*.zsh(N))
    source $snippets
# }}}
