" lrnt's vim configuration file

" {{{ Basics
execute pathogen#infect()

set nocompatible
set modelines=5
set list
set listchars=tab:▸\ ,eol:¬
set relativenumber
set ruler
set cursorline
set mouse=a

filetype plugin on

let mapleader=","

" Sudo to write
cnoremap w!! w !sudo tee % >/dev/null

" Spell check language
set spelllang=en_us
map <F5> :setlocal spell!<CR>
" }}}

" {{{ Tabs and wrapping
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set autoindent
set wrap
set formatoptions=n1
set textwidth=80
set colorcolumn=+1
" }}}

" {{{ Looks
syntax on
set background=dark
colorscheme solarized
set statusline=%F%m%r%h%w%=(%{&ff}/%Y)\ (line\ %l\/%L,\ col\ %c)
set laststatus=2
set foldmethod=marker

if has('gui_running')
    set guifont=Terminus\ 10

    " Less UI stuff
    set go-=T
    set go-=l
    set go-=L
    set go-=r
    set go-=R

    " Beautiful vertical lines
    set fillchars=vert:│
endif

if has("autocmd")
    " Jump to last position when reopening a file...
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
        \| exe "normal! g'\"" | endif

    " ... except for commit messages
    au BufReadPost COMMIT_EDITMSG
        \ exe "normal! gg"
endif
" }}}

" {{{ Navigation
" Navigation between split windows
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l
nnoremap <c-r> <c-w>r

" Easy edit and view
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :edit %%
map <leader>v :view %%

" CtrlP
nnoremap <leader>f :CtrlP .<cr>
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(pyc)$',
  \ }

" Annoying keys
nnoremap <F1> <nop>
nnoremap Q <nop>
nnoremap K <nop>
" }}}

" {{{ Backup files
set undodir=~/.vim/tmp/undo//
set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//
set backup
" }}}
