# lrnt's zsh configuration file

# {{{ Environment
export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
export VISUAL="gvim -f"
export EDITOR="${visual}"
export BROWSER="/usr/bin/firefox"
export XTERM="urxvt"
export PATH=$PATH:$HOME/bin:/opt/android-sdk/tools
export DOTFILES="$HOME/dotfiles"
# }}}

# {{{ Options
autoload -U colors && colors
autoload -U compinit && compinit
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

setopt prompt_subst

# Smart urls
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
# }}}

# {{{ Keybindings
bindkey "$terminfo[kich1]"  overwrite-mode

bindkey "$terminfo[khome]"  vi-beginning-of-line
bindkey "$terminfo[kend]"   vi-end-of-line

bindkey "$terminfo[kpp]"    beginning-of-buffer-or-history
bindkey "$terminfo[knp]"    end-of-buffer-or-history

bindkey "$terminfo[kcub1]"  backward-char
bindkey "$terminfo[kcuf1]"   forward-char

bindkey "$terminfo[kLFT]"   vi-backward-word
bindkey "$terminfo[kRIT]"   vi-forward-word

bindkey "\eOc" forward-word
bindkey "\eOd" backward-word
bindkey "\eOa" vi-forward-word
bindkey "\eOb" vi-backward-word
# }}}

# {{{ Load snippets
for snippets ($DOTFILES/zsh/*.zsh(N))
    source $snippets
# }}}
